[project]
name = 'synca_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.anonymization]
path = 'contracts/anonymization.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_shearing_and_consent_management]
path = 'contracts/data_shearing_and_consent_management.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_storage]
path = 'contracts/data_storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_validation]
path = 'contracts/data_validation.clar'
clarity_version = 2
epoch = 2.5

[contracts.impact_report]
path = 'contracts/impact_report.clar'
clarity_version = 2
epoch = 2.5

[contracts.research_funding]
path = 'contracts/research_funding.clar'
clarity_version = 2
epoch = 2.5

[contracts.user_identity]
path = 'contracts/user_identity.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
